string=list(('hello','thundersoft','india','good morning'))
print(string)
print(type(string))
print(string[-1])
i=(10,20,30,40,50)
print(type(i))
print(list(i))
a=(True,False,True,False,False,True,False)
print(a)
print(type(a))
b=list(a)
print(b)
print(type(b))
print(b[-1])

